version: '3.7'

services:
  mongo-express:
    image: mongo-express:0.54.0
#    restart: on-failure
    ports:
      - 8889:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
    links:
      - mongo:mongo
    networks:
      - wishlist-compose-network

  mongo:
    image: docker.io/mongo:5
    container_name: mongo
    environment:
#      MONGO_INITSCRIPTS_DIR: /docker-entrypoint-initdb.d
      MONGO_INITDB_DATABASE: wishlistDB
      MONGO_DATABASE: wishlistDB
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
#      - ./mongo_setup:/docker-entrypoint-initdb.d/
#      - ./mongo_data:/data/db
    networks:
      - wishlist-compose-network

networks:
  mongo-compose-network:
    driver: bridge